package net.nurlans.jobnomad.model.status;

public enum Country {
    KYRGYZSTAN, KAZAKHSTAN, UZBEKISTAN, TAJIKISTAN,
    USA, UAE, RUSSIA, UKRAINE, BELARUS, GERMANY,
    POLAND, TURKEY, ENGLAND, HUNGARY,
    SOUTH_KOREA, JAPAN, INDIA, CANADA, LITHUANIA,
    ESTONIA, AUSTRIA, ITALY, SPAIN, FRANCE, SWEDEN,
    NORWAY, DENMARK, AUSTRALIA
}
